name: "Build Docker images"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    if: github.repository == 'u1f408/x'
    steps:
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command go mod download
    - run: nix develop --command make

    - run: |
        for binary in "uppy"; do
          for tag in latest ${{ env.BRANCH_NAME }} ${{ github.sha }}; do
            cat Dockerfile.bin | sed "s/__BINARY__/$binary/g" | docker build -t ghcr.io/u1f408/$binary:$tag -f - .
          done
          if [ "${{ github.repository }}" == "u1f408/x" ]; then
            docker push ghcr.io/u1f408/$binary:${{ env.BRANCH_NAME }}
            docker push ghcr.io/u1f408/$binary:${{ github.sha }}
            [ "${{ env.BRANCH_NAME }}" == "main" ] && docker push ghcr.io/u1f408/$binary:latest
          fi
        done
